services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # Service token per consentire l'accesso a Kibana
      - "./elastic/config/service_tokens:/usr/share/elasticsearch/config/service_tokens"
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # Username and password are no longer supported, must use service account tokens
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2VsYXN0aWMta2liYW5hLXRva2VuOjMwclV3THZjUWw2aW54WDFDX3RmX3c
    ports:
      - "5601:5601"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q '302 Found'" ]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    environment:
      - KAFKA_ADDRESS=kafka-broker:9092
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
    # Non serve esporle per questo progetto
    #ports:
    #  - "5044:5044"
    #  - "9600:9600"
    depends_on:
      elasticsearch:
        condition: service_healthy

  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,CONTROLLER://kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    # Non serve esporle per questo progetto
    #ports:
    #  - "9092:9092"
    #  - "9093:9093"

  house:
    #container_name: house # Non disponibile se sono molteplici (replicas)
    build:
      context: house
      args:
        - STACK_VERSION=${STACK_VERSION}
    environment:
      - SIMULATION_START=${SIMULATION_START}
      - SIMULATION_STEP=${SIMULATION_STEP}
      - SIMULATION_SPEED=${SIMULATION_SPEED}
      - SIMULATION_HOW_MANY_STEPS=${SIMULATION_HOW_MANY_STEPS}
      - KAFKA_ADDRESS=kafka-broker:9092
    deploy:
      replicas: ${HOUSES}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      startup-elastic:
        condition: service_completed_successfully
      startup-kibana:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "[ $(wc -l /app/log.ndjson | awk '{print $1}') -gt 5 ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
    # Utile durante lo sviluppo
    #develop:
    #  watch:
    #  - action: rebuild
    #    path: ./house
    #    target: /app

  startup-elastic:
    build: elastic
    environment:
      - ELASTIC_ADDRESS=elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  startup-kibana:
    build: kibana
    environment:
      - KIBANA_ADDRESS=kibana:5601
    depends_on:
      kibana:
        condition: service_healthy

  elaboration:
    build: elaboration
    environment:
      - SIMULATION_START=${SIMULATION_START}
      - SIMULATION_STEP=${SIMULATION_STEP}
      - SIMULATION_SPEED=${SIMULATION_SPEED}
      - ELASTIC_ADDRESS=elasticsearch:9200
    depends_on:
      house:
        condition: service_healthy
